Repository mdsreq-fga-unb/2024.2-T03-PanelasGrill, pull requests merged in 2024-11, with the labels that each got.

#2 1 iniciar o gitpages
  Panelas_Grill/docs/imagens/Panelas_Grill.jpeg
  Panelas_Grill/docs/index.md
  Panelas_Grill/mkdocs.yml
  README.md
Labels: documentation

#10 3 adicionar cenário atual do cliente e do negocio no pages
  Panelas_Grill/docs/imagens/diagrama.png
  Panelas_Grill/docs/index.md
  Panelas_Grill/docs/sessao1.md
  Panelas_Grill/mkdocs.yml
  README.md
Labels: documentation

#14 [DOC] Atualizando o Tópico 2 com Novas Tecnologias
  docs/unidade1/sessao2.md
Labels: documentation

#15 [DOC] Adicionando Políticas de Boas Práticas
  docs/Politicas/politica_branch.md
  docs/Politicas/politica_commit.md
  docs/Politicas/politica_issue.md
Labels: documentation

#18 [DOC] Adicionando políticas de boas práticas
  docs/Politicas/politica_branch.md
  docs/Politicas/politica_commit.md
  docs/Politicas/politica_issue.md
  mkdocs.yml
Labels: documentation

#24 Alterações na estrategia.
  docs/imagens/GUPTA1.jpg
  docs/imagens/GUPTA2.jpg
  docs/unidade1/sessao3.md
  docs/unidade1/sessao4.md
Labels: product and project vision, enhancement

#25 [DOCS] Realizando as alterações seguindo o feedback do Professor
  docs/imagens/diagrama.png
  docs/unidade1/sessao1.md
  docs/unidade1/sessao2.md
  docs/unidade1/sessao5.md
Labels: product and project vision
